### ISSUE TITLE
Problem on wordpress

### ISSUE THREAD

**Issue by davidki11** [thdoan/pretty-dropdowns#1]
Hi Tom.

I have a website on wordpress. I implemented your plugin. Everything work and I see nice dropdown on my website. But I see some errors in console and your plugin causes malfunction of some of my other plugins.

Developer of my theme wrote to me that the problem is that wordpress already has jquery.js library and it's loaded with wordpress by defaul, and therefore plugins don't need this library, because it's loaded with wordpress by default.

But your plugin load it too:

<script src="//ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
I try to deleted this link to jquery, but in this case your plugin doesn’t work.
Please can you help me? What can I do to make your plugin work correctly on wordpress? 

Thank you very much, David

**Comment by thdoan** [comment]
Hi David, if jQuery is already present, then remove `<script src="//ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>`, but make sure that `<script src="//cdn.rawgit.com/thdoan/pretty-dropdowns/master/dist/js/jquery.prettydropdowns.js"></script>` is loaded after jQuery since this plugin requires jQuery.

**Comment by thdoan** [comment]
Auto-close after a week of inactivity...
